import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { tanstackRouter } from '@tanstack/router-plugin/vite'
import { VitePWA } from 'vite-plugin-pwa'
import type { Plugin } from 'vite'

/**
 * The prerendered documents in `public/`, by the path a link uses. GitHub
 * Pages answers `/glossary` with `glossary/index.html` and `/privacy` with
 * `privacy.html`; Vite's dev server does neither — an extensionless path
 * falls through to the app shell and the router says Not Found for a page
 * that is right there on disk. The list is spelled out rather than read off
 * the disk because the config is typed without Node's `fs`, and it is the
 * same set the service worker's `navigateFallbackDenylist` names below: a
 * document added to one belongs in the other.
 */
const PUBLIC_DOCUMENTS: Record<string, string> = {
  '/privacy': '/privacy.html',
  '/terms': '/terms.html',
  '/glossary': '/glossary/index.html',
  '/pollen': '/pollen/index.html',
  '/pollen/calendar': '/pollen/calendar.html',
}

/**
 * The twelve glossary term pages are a directory each, generated by
 * scripts/generate-glossary.mjs from the slugs in src/content/glossary.ts, so
 * they are matched by shape instead of being listed: a slug added to the
 * module would otherwise have to be typed out here again before it was
 * reachable in dev. Pages needs no telling — it answers `/glossary/ozone/`
 * with `glossary/ozone/index.html` on its own.
 */
const GLOSSARY_TERM = /^\/glossary\/[a-z0-9-]+$/

/** Dev only: serve those documents the way Pages does. The build copies `public/` verbatim. */
const publicDocuments = (): Plugin => ({
  name: 'public-documents',
  configureServer(server) {
    server.middlewares.use((req, _res, next) => {
      // Typed by hand: the config compiles without Node's types, so
      // `IncomingMessage` is an empty shape here.
      const request = req as { url?: string }
      const url = new URL(request.url ?? '/', 'http://localhost')
      const path = url.pathname.replace(/\/+$/, '')
      const file =
        PUBLIC_DOCUMENTS[path] ?? (GLOSSARY_TERM.test(path) ? `${path}/index.html` : undefined)
      if (file !== undefined) request.url = file + url.search
      next()
    })
  },
})

export default defineConfig({
  base: '/',
  plugins: [
    publicDocuments(),
    tanstackRouter({ target: 'react', autoCodeSplitting: true }),
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      manifest: {
        name: 'Breathing Index',
        short_name: 'Breathing',
        description:
          'A personal air index that learns your triggers from your own breathing logs and tells you how today compares, on a four-level scale from 1 (Easy) to 4 (Dangerous).',
        theme_color: '#F3F6F7',
        background_color: '#F3F6F7',
        display: 'standalone',
        icons: [
          { src: 'icons/icon-192.png', sizes: '192x192', type: 'image/png' },
          { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png' },
          {
            src: 'icons/maskable-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        // Workbox precaches js/wasm/css/html by default; the self-hosted fonts
        // have to be named or the installed app falls back to system type.
        globPatterns: ['**/*.{js,wasm,css,html,woff2}'],
        // /privacy, /terms and the /pollen and /glossary pages are real
        // documents served off disk, not app routes. Without this the
        // navigation fallback answers them from the precached index.html and
        // an installed PWA never sees them.
        navigateFallbackDenylist: [/^\/privacy/, /^\/terms/, /^\/pollen/, /^\/glossary/],
        runtimeCaching: [
          {
            urlPattern: /^https:\/\/(air-quality-api|api)\.open-meteo\.com\/.*/,
            handler: 'NetworkFirst',
            options: {
              cacheName: 'open-meteo',
              networkTimeoutSeconds: 8,
              expiration: { maxEntries: 24, maxAgeSeconds: 6 * 3600 },
            },
          },
          {
            // Place names for a given coordinate essentially never change, so
            // this one is cache-first — it keeps the header named when offline.
            urlPattern: /^https:\/\/api\.bigdatacloud\.net\/data\/reverse-geocode-client.*/,
            handler: 'CacheFirst',
            options: {
              cacheName: 'reverse-geocode',
              expiration: { maxEntries: 16, maxAgeSeconds: 30 * 24 * 3600 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
    }),
  ],
})
