import type { Priors } from './types'

/**
 * Background floors: an exposure at or below this can never become a suspect,
 * even with no tolerance evidence. These encode "measurably present," not
 * "harmful" — they sit well below any health-relevant level.
 */
const NEGLIGIBLE: Record<string, number> = {
  pm25: 5, // µg/m³
  pm10: 10,
  o3: 20,
  no2: 10,
  so2: 5,
  co: 300,
  heat_stress: 0, // any positive stress is non-negligible
  cold_dry_stress: 0,
  humidity: 55, // %RH mean72h below this is not a mold-proxy candidate
  grass_pollen: 2, // grains/m³
  ragweed_pollen: 1,
  birch_pollen: 2,
}

export function negligibleFor(variable: string): number {
  return NEGLIGIBLE[variable] ?? 0
}

/**
 * Variables that proxy indoor exposure. The "worse-outdoors" observation
 * removes these from an entry's candidate sets: symptoms tied to being
 * outside can't be blamed on the indoor-air proxy.
 */
export const INDOOR_PROXY_VARIABLES: ReadonlySet<string> = new Set(['humidity'])

/**
 * Population priors, ceiling-only: "at this exposure, a sensitive person is
 * *potentially* at this level." Personal diary evidence replaces these.
 *
 * The pollutant rows are generated by `scripts/derive-breakpoints.mjs`, which holds
 * the published tables in their published units and does the ppb -> µg/m³ conversion;
 * `npm test` fails if the block below drifts from it. Edit the script, then run
 * `node scripts/derive-breakpoints.mjs --write`. Each row names its source, because
 * they are not all the same source: PM and ozone are EPA AQI breakpoints, while
 * no2/so2/co are WHO (and one EU) guideline values, which are stricter than EPA's
 * breakpoints for those gases. Weather/pollen rows below are heuristic starts.
 *
 * Two honesty notes about comparing these to what the app actually measures:
 *
 * 1. **Instantaneous vs averaged.** The published breakpoints are averages — 24-h
 *    means for PM, 8-h for ozone and CO, 1-h or 24-h for the WHO gases — but the
 *    engine compares them against features built from the current hour and an 8-h
 *    running max (docs/trigger-model.md). A single bad hour can therefore cross a
 *    24-h breakpoint that a real 24-h mean would not. The bias is toward warning
 *    early, which is the right direction for a ceiling that only ever *raises* a
 *    prediction and is superseded by the user's own diary — but the numbers are not
 *    AQI categories, and nothing in the UI should claim they are.
 * 2. **Which end of the category.** Every row is the *lower* bound of its category:
 *    the exposure at which a category begins, not its midpoint. That is what makes
 *    "potentially at this level" true at the threshold rather than halfway past it.
 */
export const PRIORS: Priors = {
  // --- derived by scripts/derive-breakpoints.mjs — edit there, not here ---
  // EPA AQI table (2024 PM2.5 revision), 24-h mean, published in µg/m³ — no conversion.
  //   2 = Moderate 9.1 · 3 = USG 35.5 · 4 = Unhealthy 55.5
  pm25: { 2: 9.1, 3: 35.5, 4: 55.5 }, // µg/m³
  // EPA AQI table, 24-h mean, published in µg/m³ — no conversion.
  //   2 = Moderate 55 · 3 = USG 155 · 4 = Unhealthy 255
  pm10: { 2: 55, 3: 155, 4: 255 }, // µg/m³
  // EPA AQI table, 8-h mean, published in ppb -> µg/m³ at 25 °C / 1013 hPa. Level 2 is
  // the WHO 2021 8-h guideline instead: stricter than EPA Moderate (55 ppb ≈ 108 µg/m³),
  // which is what a sensitive-user ceiling wants.
  //   2 = WHO 8-h AQG 100 · 3 = EPA USG 71 ppb ×1.96 = 139 · 4 = EPA Unhealthy 86 ppb ×1.96 = 169
  o3: { 2: 100, 3: 139, 4: 169 }, // µg/m³
  // WHO 2021 air quality guidelines, published in µg/m³ — not EPA, and deliberately
  // stricter than it: EPA 1-h USG starts at 101 ppb ≈ 190 µg/m³. Level 3 is a hand-set
  // step between the two WHO numbers, not a published breakpoint.
  //   2 = WHO 24-h AQG 25 · 3 = hand-set 100 · 4 = WHO 1-h guideline 200
  no2: { 2: 25, 3: 100, 4: 200 }, // µg/m³
  // WHO / EU guidelines, published in µg/m³ — not EPA, and stricter than it: EPA 1-h USG
  // starts at 76 ppb ≈ 199 µg/m³.
  //   2 = WHO 2021 24-h AQG 40 · 3 = WHO 2005 24-h IT-1 125 · 4 = EU 1-h limit 350
  so2: { 2: 40, 3: 125, 4: 350 }, // µg/m³
  // WHO guidelines, published in mg/m³, written here in µg/m³ (×1000) to match the rest
  // of the engine. Level 4 is hand-set and sits just *above* EPA 8-h Unhealthy
  // (12.5 ppm ≈ 14313 µg/m³) — the one row that is not conservative against EPA.
  //   2 = WHO 24-h AQG 4000 · 3 = WHO 8-h guideline 10000 · 4 = hand-set 15000
  co: { 2: 4000, 3: 10000, 4: 15000 }, // µg/m³
  // --- end derived ---
  heat_stress: { 2: 7, 3: 12 }, // °C above 25
  cold_dry_stress: { 2: 10, 3: 18 }, // °C below 10, dry air
  humidity: { 2: 70 }, // %RH mean72h, indoor mold/dust-mite proxy
  ragweed_pollen: { 2: 10, 3: 50 }, // grains/m³
  grass_pollen: { 2: 20, 3: 100 },
  birch_pollen: { 2: 30, 3: 90 },
}
